# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

dist: goreleaser-dist

before:
  hooks:
    - rustup default stable
    - cargo install --locked --force cargo-zigbuild

brews:
  - name: globetrotter
    ids:
      - globetrotter
    description: "Polyglot, type-safe internationalization"
    directory: Formula
    commit_author:
      name: roman
      email: roman@luup-systems.com
    repository:
      owner: LuupSystems
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false

builds:
  - id: "globetrotter"
    builder: rust
    binary: globetrotter
    # see: https://doc.rust-lang.org/nightly/rustc/platform-support.html
    targets:
      # linux
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      # macos works only for zig<0.14 (unable to open library directory '/opt/MacOSX11.3.sdk/opt/MacOSX11.3.sdk/usr/lib': FileNotFound)
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      # windows (gnu) works only for zig>=0.14
      # - x86_64-pc-windows-gnu
      # - aarch64-pc-windows-gnullvm
      # windows (msvc) doesnt work right now, requires windows.h from msvc
      # - x86_64-pc-windows-msvc
      # - aarch64-pc-windows-msvc
    dir: ./
    tool: cargo
    command: zigbuild
    flags:
      - "--release"
      - "--package=globetrotter-cli"
      - "--bin=globetrotter"
      - "--target-dir=./target" # TODO: can we remove this once rust support is better?

archives:
  - id: globetrotter
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - globetrotter
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"

release:
  draft: false
