# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  default:
    cmds:
      - task: run

  run:
    desc: "run"
    cmds:
      - cargo run -p globetrotter-cli -- {{.CLI_ARGS}}

  build:
    desc: "build in debug mode"
    cmds:
      - cargo build --all-targets {{.CLI_ARGS}}

  build:fc:
    desc: "build cargo workspace for each combination of features"
    cmds:
      - cargo fc build --workspace --all-targets {{.CLI_ARGS}}

  build:release:
    desc: "build in release mode"
    cmds:
      - cargo build --all-targets --release {{.CLI_ARGS}}

  build:env:
    internal: true
    cmds:
      - docker build --load -t build-env -f ./docker/build_env.dockerfile .

  build:goreleaser:
    desc: "cross compile using goreleaser"
    deps: [build:env]
    cmds:
      # pretter-ignore
      - >-
        docker run --rm
        -v "${PWD}:/workspace"
        -w /workspace
        build-env
        bash -c 'source ./release.sh && goreleaser build --snapshot --clean --timeout 120m'

  release:
    desc: "release using goreleaser"
    deps: [build:env]
    cmds:
      # pretter-ignore
      - >-
        docker run --rm
        -e "GITHUB_TOKEN=${GITHUB_TOKEN}"
        -e "TAP_GITHUB_TOKEN=${TAP_GITHUB_TOKEN}"
        -v "${PWD}:/workspace"
        -w /workspace
        build-env
        bash -c 'source ./release.sh && goreleaser release --clean --timeout 120m'

  typos:
    desc: "check repository for typos"
    aliases: [spellcheck]
    cmds:
      - typos

  check:
    desc: "check cargo workspace"
    cmds:
      - cargo check --workspace --all-targets {{.CLI_ARGS}}

  check:fc:
    desc: "check cargo workspace"
    cmds:
      - cargo fc check --workspace --all-targets {{.CLI_ARGS}}

  clean:
    desc: "clean cargo workspace"
    cmds:
      - cargo clean {{.CLI_ARGS}}

  docs:
    desc: "open documentation preview"
    env:
      RUSTDOCFLAGS: "--cfg docsrs"
    cmds:
      - cargo +nightly watchdoc --all-features {{.CLI_ARGS}}

  outdated:
    desc: "check for outdated cargo workspace dependencies"
    cmds:
      - cargo outdated --workspace --ignore-external-rel --exit-code 1 -v {{.CLI_ARGS}}

  unused:
    desc: "check for unused cargo workspace dependencies"
    aliases: [unused-dependencies]
    cmds:
      - cargo +nightly udeps {{.CLI_ARGS}}

  audit:
    desc: "audit cargo workspace dependencies"
    cmds:
      - cargo audit {{.CLI_ARGS}}

  format:
    desc: "format cargo workspace"
    cmds:
      - cargo fmt --all {{.CLI_ARGS}}

  test:
    desc: "test cargo workspace"
    cmds:
      - cargo nextest run --workspace --all-targets --no-tests "warn" {{.CLI_ARGS}}

  test:fc:
    desc: "test cargo workspace for all combinations of features"
    cmds:
      - cargo fc nextest run --workspace --all-targets --no-tests "warn" {{.CLI_ARGS}}

  test:doc:
    desc: "run doctests in cargo workspace"
    cmds:
      - cargo test --doc {{.CLI_ARGS}}

  lint:
    desc: "lint cargo workspace"
    cmds:
      - cargo lint --workspace --all-features {{.CLI_ARGS}}

  lint:fc:
    desc: "lint cargo workspace for all combinations of features"
    cmds:
      - cargo fc lint {{.CLI_ARGS}}

  lint:fix:
    desc: "lint and fix cargo workspace"
    aliases: [fix]
    cmds:
      - cargo fixit --workspace --all-features {{.CLI_ARGS}}

  lint:actions:
    desc: "lint github actions"
    cmds:
      - actionlint
