//! TypeScript bindings code generation for globetrotter translations.

/// TypeScript code generation configuration types.
pub mod config;

#[cfg(feature = "swc")]
mod ast_swc;

#[cfg(feature = "swc")]
pub use ast_swc::Error;
#[cfg(feature = "swc")]
pub use ast_swc::generate_translations_type_export;

pub use config::OutputConfig;

/// Common header inserted at the top of generated TypeScript files.
#[must_use]
pub fn preamble() -> String {
    unindent::unindent(&format!(
        "\
        //
        // AUTOGENERATED. DO NOT EDIT.
        // generated by globetrotter v{}.
        //
        ",
        std::env!("CARGO_PKG_VERSION"),
    ))
}

// Keep test setup unavailable when the SWC backend itself is absent.
#[cfg(all(test, feature = "swc"))]
pub(crate) mod tests {
    static INIT: std::sync::Once = std::sync::Once::new();

    /// Installs `color_eyre` once for tests that return reports.
    pub fn init() {
        INIT.call_once(|| {
            color_eyre::install().ok();
        });
    }
}
