[package]
name = "globetrotter-cli"
license = "MIT"
readme = "../../README.md"
documentation = "https://docs.rs/globetrotter-cli"
publish = true

version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
categories = [
  "command-line-utilities",
  "internationalization",
  "localization",
]
keywords = [
  "i8n",
  "internationalization",
  "translations",
]

[lints]
workspace = true

[features]
default = [
  "typescript",
  "rust",
  "golang",
  "python",
]
typescript = ["globetrotter/typescript"]
rust = ["globetrotter/rust"]
golang = ["globetrotter/golang"]
python = ["globetrotter/python"]

[package.metadata.cargo-feature-combinations]
exclude_features = ["default"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bin]]
name = "globetrotter"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
futures.workspace = true
color-eyre.workspace = true
strum.workspace = true
thiserror.workspace = true

# colors and diagnostics
termcolor = "1"
codespan-reporting.workspace = true

# argument parsing
clap.workspace = true

# logging
tracing.workspace = true
tracing-subscriber = { version = "0", features = ["json", "env-filter"] }

globetrotter.workspace = true
handlebars.workspace = true

# format: sort translation files while preserving comments
toml_edit = "0"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0"

[dev-dependencies]
color-eyre.workspace = true
similar-asserts.workspace = true
indoc.workspace = true
