# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: build
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  MISE_GITHUB_TOKEN: ${{ github.token }}
  MISE_AUTO_INSTALL: "0"

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    outputs:
      precompiled-binaries: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v4
        with:
          version: 2026.7.16
          install: false
          cache: true
          env: false
      - run: mise install task
      - name: Release (dry-run)
        run: task build:goreleaser
      - name: Upload precompiled binaries
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: goreleaser-dist
          path: goreleaser-dist

  build-container:
    runs-on: ubuntu-24.04
    needs: [goreleaser]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v7
      - name: Download precompiled binaries
        uses: actions/download-artifact@v8
        with:
          name: goreleaser-dist
          path: goreleaser-dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build multi-arch container
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/package_precompiled.dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/luupsystems/globetrotter:latest
            ghcr.io/luupsystems/globetrotter:${{ github.ref_name }}
