name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish-crate:
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates
        uses: romnn/publish-crates@main
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          resolve-versions: true
          publish-delay: 30s

  publish-container:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build multi-arch container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/globetrotter:latest
            ghcr.io/${{ github.repository }}/globetrotter:${{ github.ref_name }}

  release:
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: task release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAP_GITHUB_TOKEN: "${{ secrets.TAP_GITHUB_TOKEN }}"
